language: node_js
node_js:
  - 14
before_script:
  - yarn
script: stylus --compress ./stylus/ --out ./eleventy-stylus-blog-theme/static/css/ && eleventy --pathprefix=eleventy-stylus-blog-theme
deploy:
  local-dir: _site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  target_branch: gh-pages
  on:
    branch: main
